CTFd/utils/user/__init__.py
from flask import current_app as app, session, request
from CTFd.models import Users
from CTFd.utils import get_config
from CTFd.models import db, Fails
import datetime
import re


def get_current_user():
    if authed():
        user = Users.query.filter_by(id=session["id"]).first()
        return user
    else:
        return None


def get_current_team():
    if authed():
        user = get_current_user()
        return user.team
    else:
        return None


def authed():
    return bool(session.get("id", False))


def is_admin():
    if authed():
        return session["type"] == "admin"
    else:
        return False


def is_verified():
    if get_config("verify_emails"):
        user = get_current_user()
        if user:
            return user.verified
        else:
            return False
    else:
        return True


def get_ip(req=None):
    """ Returns the IP address of the currently in scope request. The approach is to define a list of trusted proxies
     (in this case the local network), and only trust the most recently defined untrusted IP address.
     Taken from http://stackoverflow.com/a/22936947/4285524 but the generator there makes no sense.
     The trusted_proxies regexes is taken from Ruby on Rails.

     This has issues if the clients are also on the local network so you can remove proxies from config.py.

     CTFd does not use IP address for anything besides cursory tracking of teams and it is ill-advised to do much
     more than that if you do not know what you're doing.
    """
    if req is None:
        req = request
    trusted_proxies = app.config["TRUSTED_PROXIES"]
    combined = "(" + ")|(".join(trusted_proxies) + ")"
    route = req.access_route + [req.remote_addr]
    for addr in reversed(route):
        if not re.match(combined, addr):  # IP is not trusted but we trust the proxies
            remote_addr = addr
            break
    else:
        remote_addr = req.remote_addr
    return remote_addr


def get_wrong_submissions_per_minute(account_id):
    """
    Get incorrect submissions per minute.

    :param account_id:
    :return:
    """
    one_min_ago = datetime.datetime.utcnow() + datetime.timedelta(minutes=-1)
    fails = (
        db.session.query(Fails)
        .filter(Fails.account_id == account_id, Fails.date >= one_min_ago)
        .all()
    )
    return len(fails)

CTFd/views.py
from flask import (
    current_app as app,
    render_template,
    request,
    redirect,
    abort,
    url_for,
    session,
    Blueprint,
    Response,
    send_file,
)
from flask.helpers import safe_join

from CTFd.models import db, Users, Admins, Teams, Files, Pages, Notifications
from CTFd.utils import markdown
from CTFd.cache import cache
from CTFd.utils import get_config, set_config
from CTFd.utils.user import authed, get_current_user
from CTFd.utils import config
from CTFd.utils.uploads import get_uploader
from CTFd.utils.config.pages import get_page
from CTFd.utils.config.visibility import challenges_visible
from CTFd.utils.security.auth import login_user
from CTFd.utils.security.csrf import generate_nonce
from CTFd.utils import user as current_user
from CTFd.utils.dates import ctftime, ctf_ended, view_after_ctf
from CTFd.utils.decorators import authed_only
from CTFd.utils.security.signing import (
    unserialize,
    BadTimeSignature,
    SignatureExpired,
    BadSignature,
)
from sqlalchemy.exc import IntegrityError
import os


views = Blueprint("views", __name__)


@views.route("/setup", methods=["GET", "POST"])
def setup():
    if not config.is_setup():
        if not session.get("nonce"):
            session["nonce"] = generate_nonce()
        if request.method == "POST":
            ctf_name = request.form["ctf_name"]
            set_config("ctf_name", ctf_name)

            # CSS
            set_config("start", "")

            # Admin user
            name = request.form["name"]
            email = request.form["email"]
            password = request.form["password"]
            admin = Admins(
                name=name, email=email, password=password, type="admin", hidden=True
            )

            user_mode = request.form["user_mode"]

            set_config("user_mode", user_mode)

            # Index page

            index = """<div class="row">
    <div class="col-md-6 offset-md-3">
        <img class="w-100 mx-auto d-block" style="max-width: 500px;padding: 50px;padding-top: 14vh;" src="themes/core/static/img/logo.png" />
        <h3 class="text-center">
            <p>A cool CTF platform from <a href="https://ctfd.io">ctfd.io</a></p>
            <p>Follow us on social media:</p>
            <a href="https://twitter.com/ctfdio"><i class="fab fa-twitter fa-2x" aria-hidden="true"></i></a>&nbsp;
            <a href="https://facebook.com/ctfdio"><i class="fab fa-facebook fa-2x" aria-hidden="true"></i></a>&nbsp;
            <a href="https://github.com/ctfd"><i class="fab fa-github fa-2x" aria-hidden="true"></i></a>
        </h3>
        <br>
        <h4 class="text-center">
            <a href="admin">Click here</a> to login and setup your CTF
        </h4>
    </div>
</div>""".format(
                request.script_root
            )

            page = Pages(title=None, route="index", content=index, draft=False)
            # Visibility
            set_config("challenge_visibility", "private")
            set_config("registration_visibility", "public")
            set_config("score_visibility", "public")
            set_config("account_visibility", "public")

            # Start time
            set_config("start", None)
            set_config("end", None)
            set_config("freeze", None)

            # Verify emails
            set_config("verify_emails", None)

            set_config("mail_server", None)
            set_config("mail_port", None)
            set_config("mail_tls", None)
            set_config("mail_ssl", None)
            set_config("mail_username", None)
            set_config("mail_password", None)
            set_config("mail_useauth", None)

            set_config("setup", True)

            try:
                db.session.add(admin)
                db.session.commit()
            except IntegrityError:
                db.session.rollback()

            try:
                db.session.add(page)
                db.session.commit()
            except IntegrityError:
                db.session.rollback()

            login_user(admin)

            db.session.close()
            app.setup = False
            with app.app_context():
                cache.clear()

            return redirect(url_for("views.static_html"))
        return render_template("setup.html", nonce=session.get("nonce"))
    return redirect(url_for("views.static_html"))


@views.route("/notifications", methods=["GET"])
def notifications():
    notifications = Notifications.query.order_by(Notifications.id.desc()).all()
    return render_template("notifications.html", notifications=notifications)


@views.route("/settings", methods=["GET"])
@authed_only
def settings():
    user = get_current_user()
    name = user.name
    email = user.email
    website = user.website
    affiliation = user.affiliation
    country = user.country
    prevent_name_change = get_config("prevent_name_change")
    confirm_email = get_config("verify_emails") and not user.verified
    return render_template(
        "settings.html",
        name=name,
        email=email,
        website=website,
        affiliation=affiliation,
        country=country,
        prevent_name_change=prevent_name_change,
        confirm_email=confirm_email,
    )


@views.route("/static/user.css")
def custom_css():
    """
    Custom CSS Handler route
    :return:
    """
    return Response(get_config("css"), mimetype="text/css")


@views.route("/", defaults={"route": "index"})
@views.route("/<path:route>")
def static_html(route):
    """
    Route in charge of routing users to Pages.
    :param route:
    :return:
    """
    page = get_page(route)
    if page is None:
        abort(404)
    else:
        if page.auth_required and authed() is False:
            return redirect(url_for("auth.login", next=request.full_path))

        return render_template("page.html", content=markdown(page.content))


@views.route("/files", defaults={"path": ""})
@views.route("/files/<path:path>")
def files(path):
    """
    Route in charge of dealing with making sure that CTF challenges are only accessible during the competition.
    :param path:
    :return:
    """
    f = Files.query.filter_by(location=path).first_or_404()
    if f.type == "challenge":
        if challenges_visible():
            if current_user.is_admin() is False:
                if not ctftime():
                    if ctf_ended() and view_after_ctf():
                        pass
                    else:
                        abort(403)
        else:
            if not ctftime():
                abort(403)

            # Allow downloads if a valid token is provided
            token = request.args.get("token", "")
            try:
                data = unserialize(token, max_age=3600)
                user_id = data.get("user_id")
                team_id = data.get("team_id")
                file_id = data.get("file_id")
                user = Users.query.filter_by(id=user_id).first()
                team = Teams.query.filter_by(id=team_id).first()

                # Check user is admin if challenge_visibility is admins only
                if (
                    get_config("challenge_visibility") == "admins"
                    and user.type != "admin"
                ):
                    abort(403)

                # Check that the user exists and isn't banned
                if user:
                    if user.banned:
                        abort(403)
                else:
                    abort(403)

                # Check that the team isn't banned
                if team:
                    if team.banned:
                        abort(403)
                else:
                    pass

                # Check that the token properly refers to the file
                if file_id != f.id:
                    abort(403)

            # The token isn't expired or broken
            except (BadTimeSignature, SignatureExpired, BadSignature):
                abort(403)

    uploader = get_uploader()
    try:
        return uploader.download(f.location)
    except IOError:
        abort(404)


@views.route("/themes/<theme>/static/<path:path>")
def themes(theme, path):
    """
    General static file handler
    :param theme:
    :param path:
    :return:
    """
    filename = safe_join(app.root_path, "themes", theme, "static", path)
    if os.path.isfile(filename):
        return send_file(filename)
    else:
        abort(404)

CTFd/themes/admin/templates/users/new.html
{% extends "admin/base.html" %}

{% block stylesheets %}
{% endblock %}

{% block content %}
	<div class="jumbotron">
		<div class="container">
			<h1>
				Create User
			</h1>
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-md-6 offset-md-3">
				{% include "admin/modals/users/create.html" %}
			</div>
		</div>
	</div>
{% endblock %}

{% block scripts %}
	<script src="{{ url_for('views.themes', theme='admin', path='js/users/new.js') }}"></script>
{% endblock %}

CTFd/themes/admin/templates/users/user.html
{% extends "admin/base.html" %}

{% block stylesheets %}
{% endblock %}

{% block content %}
<div id="user-info-modal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h2 class="modal-action text-center w-100">Edit User</h2>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body clearfix">
				{% include "admin/modals/users/edit.html" %}
			</div>
		</div>
	</div>
</div>

<div id="user-award-modal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h2 class="modal-action text-center w-100">Award User</h2>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body clearfix">
				{% include "admin/modals/awards/create.html" %}
			</div>
		</div>
	</div>
</div>

<div id="user-email-modal" class="modal fade">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h2 class="modal-action text-center w-100">Email User</h2>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body clearfix">
				{% include "admin/modals/mail/send.html" %}
			</div>
		</div>
	</div>
</div>

<div class="jumbotron">
	<div class="container">
		<h1 id="team-id" class="text-center p-0 m-0">{{ user.name }}</h1>
		<div class="mb-2">
			{% if user.type == 'admin' %}
				<span class="badge badge-primary">admin</span>
			{% endif %}
			{% if user.verified %}
				<span class="badge badge-success">verified</span>
			{% endif %}
			{% if user.hidden %}
				<span class="badge badge-danger">hidden</span>
			{% endif %}
			{% if user.banned %}
				<span class="badge badge-danger">banned</span>
			{% endif %}
		</div>

		{% if user.affiliation %}
			<h3><span class="badge badge-primary">{{ user.affiliation }}</span></h3>
		{% endif %}

		<h2 id="team-email" class="text-center">{{ user.email }}</h2>
		{% if user.oauth_id %}
			<a href="https://majorleaguecyber.org/u/{{ user.name }}">
				<h3><span class="badge badge-primary">Official</span></h3>
			</a>
		{% endif %}

		{% if user.team_id %}
			<h2 id="team-acc" class="text-center">
				<a href="{{ url_for('admin.teams_detail', team_id=user.team_id) }}">
					{{ user.team.name }}
				</a>
			</h2>
		{% endif %}

		<h3 id="team-place" class="text-center">
			{% if place %}
				{{ place }}
				<small>place</small>
			{% endif %}
		</h3>
		<h3 id="team-score" class="text-center">
			{% if score %}
				{{ score }}
				<small>points</small>
			{% endif %}
		</h3>
		<div class="pt-3">
			<a class="edit-user">
				<i class="btn-fa fas fa-user-edit fa-2x px-2" data-toggle="tooltip" data-placement="top" title="Edit User"></i>
			</a>
			<a class="award-user">
				<i class="btn-fa fas fa-trophy fa-2x px-2" data-toggle="tooltip" data-placement="top" title="Award User"></i>
			</a>
			<a class="email-user">
				<i class="btn-fa fas fa-envelope fa-2x px-2" data-toggle="tooltip" data-placement="top" title="Email User"></i>
			</a>
			<a class="delete-user">
				<i class="btn-fa fas fa-trash-alt fa-2x px-2" data-toggle="tooltip" data-placement="top" title="Delete User"></i>
			</a>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		{% if solves %}
			<div id="keys-pie-graph" class="col-md-6">
				<div class="text-center">
					<i class="fas fa-circle-notch fa-spin fa-3x fa-fw spinner"></i>
				</div>
			</div>
			<div id="categories-pie-graph" class="col-md-6">
				<div class="text-center">
					<i class="fas fa-circle-notch fa-spin fa-3x fa-fw spinner"></i>
				</div>
			</div>
			<div id="score-graph" class="col-md-12">
				<div class="text-center">
					<i class="fas fa-circle-notch fa-spin fa-3x fa-fw spinner"></i>
				</div>
			</div>
		{% else %}
			<h3 class="spinner-error text-center w-100">No solves yet</h3>
		{% endif %}
	</div>


	<nav class="nav nav-tabs nav-fill pt-5" id="myTab" role="tablist">
		<a class="nav-item nav-link active" id="nav-solves-tab" data-toggle="tab" href="#nav-solves" role="tab"
		   aria-controls="nav-solves" aria-selected="true">Solves</a>

		<a class="nav-item nav-link" id="nav-wrong-tab" data-toggle="tab" href="#nav-wrong" role="tab"
		   aria-controls="nav-wrong" aria-selected="false">Fails</a>

		<a class="nav-item nav-link" id="nav-awards-tab" data-toggle="tab" href="#nav-awards" role="tab"
		   aria-controls="nav-awards" aria-selected="false">Awards</a>

		<a class="nav-item nav-link" id="nav-missing-tab" data-toggle="tab" href="#nav-missing" role="tab"
		   aria-controls="nav-missing" aria-selected="false">Missing</a>
	</nav>

	<div class="tab-content" id="nav-tabContent">
		<div class="tab-pane fade show active" id="nav-solves" role="tabpanel" aria-labelledby="nav-solves-tab">
			<div class="row">
				<div class="col-md-12">
					<table class="table table-striped">
					<h3 class="text-center py-3 d-block">Solves</h3>
					<thead>
					<tr>
						<td class="text-center"><b>Challenge</b></td>
						<td class="text-center"><b>Submitted</b></td>
						<td class="text-center"><b>Category</b></td>
						<td class="text-center"><b>Value</b></td>
						<td class="text-center"><b>Time</b></td>
						<td class="text-center"><b>Delete</b></td>
					</tr>
					</thead>
					<tbody>
					{% for solve in solves %}
						<tr class="chal-solve">
							<td class="text-center chal" id="{{ solve.challenge_id }}">
								<a href="{{ url_for("admin.challenges_detail", challenge_id=solve.challenge_id) }}">
									{{ solve.challenge.name }}
								</a>
							</td>
							<td class="flag" id="{{ solve.id }}"><pre>{{ solve.provided }}</pre></td>
							<td class="text-center">{{ solve.challenge.category }}</td>
							<td class="text-center">{{ solve.challenge.value }}</td>
							<td class="text-center solve-time">
								<script>document.write(moment("{{ solve.date|isoformat }}").local().format('MMMM Do, h:mm:ss A'))</script>
							</td>
							<td class="text-center">
								<span class="delete-submission" submission-id="{{ solve.id }}"
									  submission-type="{{ solve.type }}" submission-challenge="{{ solve.challenge.name }}" data-toggle="tooltip"
									  data-placement="top" title="Delete solve #{{ solve.id }}">
									<i class="btn-fa fas fa-times"></i>
								</span>
							</td>
						</tr>
					{% endfor %}
					</tbody>
				</table>
				</div>
			</div>
		</div>

		<div class="tab-pane fade" id="nav-wrong" role="tabpanel" aria-labelledby="nav-wrong-tab">
			<div class="row">
				<div class="col-md-12">
					<table class="table table-striped">
					<h3 class="text-center py-3 d-block">Fails</h3>
					<thead>
					<tr>
						<td class="text-center"><b>Challenge</b></td>
						<td class="text-center"><b>Submitted</b></td>
						<td class="text-center"><b>Time</b></td>
						<td class="text-center"><b>Delete</b></td>
					</tr>
					</thead>
					<tbody>
					{% for fail in fails %}
						<tr class="chal-wrong">
							<td class="text-center chal" id="{{ fail.challenge_id }}">
								<a href="{{ url_for("admin.challenges_detail", challenge_id=fail.challenge_id) }}">
									{{ fail.challenge.name }}
								</a>
							</td>
							<td class="flag" id="{{ fail.id }}">
								<pre>{{ fail.provided }}</pre>
							</td>
							<td class="text-center solve-time">
								<script>document.write(moment("{{ fail.date|isoformat }}").local().format('MMMM Do, h:mm:ss A'))</script>
							</td>
							<td class="text-center">
								<a class="delete-submission" submission-id="{{ fail.id }}"
								   submission-type="{{ fail.type }}" submission-challenge="{{ fail.challenge.name }}" data-toggle="tooltip"
									  data-placement="top" title="Delete fail #{{ fail.id }}">
									<i class="fas fa-times"></i>
								</a>
							</td>
						</tr>
					{% endfor %}
					</tbody>
				</table>
				</div>
			</div>
		</div>

		<div class="tab-pane fade" id="nav-awards" role="tabpanel" aria-labelledby="nav-awards-tab">
			<div class="row">
				<div class="col-md-12">
					<table class="table table-striped">
						<h3 class="text-center py-3 d-block">Awards</h3>
						<thead>
						<tr>
							<td class="text-center"><b>Name</b></td>
							<td class="text-center"><b>Description</b></td>
							<td class="text-center"><b>Date</b></td>
							<td class="text-center"><b>Value</b></td>
							<td class="text-center"><b>Category</b></td>
							<td class="text-center"><b>Icon</b></td>
							<td class="text-center"><b>Delete</b></td>
						</tr>
						</thead>
						<tbody id="awards-body">
						{% for award in awards %}
							<tr class="award-row">
								<td class="text-center chal" id="{{ award.id }}">{{ award.name }}</td>
								<td class=""><pre>{{ award.description }}</pre></td>
								<td class="text-center solve-time">
									<script>document.write(moment("{{ award.date|isoformat }}").local().format('MMMM Do, h:mm:ss A'))</script>
								</td>
								<td class="text-center">{{ award.value }}</td>
								<td class="text-center">{{ award.category }}</td>
								<td class="text-center">{{ award.icon }}</td>

								<td class="text-center">
									<span class="delete-award" data-toggle="tooltip"
										  data-placement="top" award-id="{{ award.id }}" award-name="{{ award.name }}"
										  title="Delete award #{{ award.id }}">
										<i class="fas fa-times"></i>
									</span>
								</td>
							</tr>
						{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>

		<div class="tab-pane fade" id="nav-missing" role="tabpanel" aria-labelledby="nav-missing-tab">
			<div class="row">
				<div class="col-md-12">
					<table class="table table-striped">
					<h3 class="text-center py-3 d-block">Missing</h3>
					<thead>
						<tr>
							<td class="text-center"><b>Challenge</b></td>
							<td class="text-center"><b>Category</b></td>
							<td class="text-center"><b>Value</b></td>
							<td class="text-center"><b>Mark Solved</b></td>
						</tr>
					</thead>
					<tbody>
					{% for challenge in missing %}
						<tr class="chal-solve">
							<td class="text-center chal" id="{{ challenge.id }}">
								<a href="{{ url_for("admin.challenges_detail", challenge_id=challenge.id) }}">
									{{ challenge.name }}
								</a>
							</td>
							<td class="text-center">{{ challenge.category }}</td>
							<td class="text-center">{{ challenge.value }}</td>
							<td class="text-center">
								<a class="correct-submission" data-toggle="tooltip" challenge-id="{{ challenge.id }}"
									  challenge-name="{{ challenge.name }}"
									  data-placement="top" title="Mark {{ challenge.name }} correct for {{ user.name }}">
									<i class="fas fa-check"></i>
								</a>
							</td>
						</tr>
					{% endfor %}
					</tbody>
				</table>
				</div>
			</div>
		</div>
	</div>

	<div class="row pt-5">
		<div class="col-md-12">
			<table class="table table-striped">
				<h3 class="text-center">IP Addresses</h3>
				<thead>
				<tr>
					<td class="text-center"><b>IP Address</b></td>
					<td class="text-center"><b>Last Seen</b></td>
				</tr>
				</thead>
				<tbody>
				{% for addr in addrs %}
					<tr>
						<td class="text-center">{{ addr.ip }}</td>
						<td class="text-center solve-time">
							<script>document.write(moment("{{ addr.date|isoformat }}").local().format('MMMM Do, h:mm:ss A'))</script>
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
	</div>

</div>

{% endblock %}

{% block scripts %}
<script>
var USER_ID = {{ user.id }};
var USER_NAME = {{ user.name | tojson }};
var TEAM_ID = {{ user.team_id | tojson }};
</script>
<script src="{{ url_for('views.themes', theme='core', path='js/vendor/plotly.min.js') }}"></script>
<script src="{{ url_for('views.themes', theme='admin', path='js/users/user.js') }}"></script>
<script src="{{ url_for('views.themes', theme='admin', path='js/users/info.js') }}"></script>
<script src="{{ url_for('views.themes', theme='admin', path='js/users/actions.js') }}"></script>
<script src="{{ url_for('views.themes', theme='admin', path='js/users/graphs.js') }}"></script>
<script>

</script>
{% endblock %}

CTFd/themes/admin/templates/users/users.html
{% extends "admin/base.html" %}

{% block stylesheets %}
{% endblock %}

{% block content %}
<div class="jumbotron">
	<div class="container">
		<h1>Users
			<span class="create-team" role="button" data-toggle="tooltip" title="Create User">
				<a href="{{ url_for('admin.users_new') }}" style="color: inherit;">
					<i class="btn-fa fas fa-plus-circle"></i>
				</a>
			</span>
		</h1>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			{% if q and field %}
			<h4 class="text-center">Searching for users with {{field}} matching {{q}}</h4>
			{% endif %}

			<form method="GET" class="form-inline">
					<div class="form-group col-md-2">
						<label for="sel1" class="sr-only" >Search Field</label>
						<select name="field" class="form-control w-100" id="sel1">
							<option value="name" {% if field == 'name' %}selected{% endif %}>Name</option>
							<option value="id" {% if field == 'id' %}selected{% endif %}>ID</option>
							<option value="email" {% if field == 'email' %}selected{% endif %}>Email</option>
							<option value="affiliation" {% if field == 'affiliation' %}selected{% endif %}>Affiliation</option>
					  </select>
					</div>
					<div class="form-group col-md-8">
						<label for="team-name-search" class="sr-only">Parameter</label>
						<input type="text" class="form-control w-100" id="team-name-search" name="q" placeholder="Search for matching team names" {% if q %}value="{{q}}"{% endif %}>
					</div>
					<div class="form-group col-md-2">
						<label for="team-name-search" class="sr-only">Search</label>
						<button type="submit" class="btn btn-primary w-100"><i class="fas fa-search" aria-hidden="true"></i></button>
					</div>
			</form>

			<br>

			<table id="teamsboard" class="table table-striped">
				<thead>
					<tr>
						<td width="10px" class="text-center"><b>ID</b>
						</td>
						<td class="text-center"><b>User</b>
						</td>
						<td class="d-md-table-cell d-lg-table-cell text-center"><b>Email</b>
						</td>
						<td class=""><b>Website</b>
						</td>
						<td class=""><b>Country</b>
						</td>
						<td class="text-center"><b>Admin</b>
						</td>
						<td class="text-center"><b>Verified</b>
						</td>
						<td class="text-center"><b>Hidden</b>
						</td>
						<td class="text-center"><b>Banned</b>
						</td>
					</tr>
				</thead>
				<tbody>
					{% for user in users %}
					<tr name="{{ user.id }}" data-href="{{ url_for('admin.users_detail', user_id=user.id) }}">
						<td class="team-id" value="{{ user.id }}">{{ user.id }}</td>
						<td class="team-name" value="{{ user.name }}">
							<a href="{{ url_for('admin.users_detail', user_id=user.id) }}">
								{{ user.name | truncate(32) }}
							</a>
							{% if user.oauth_id %}
								<a href="https://majorleaguecyber.org/u/{{ user.name }}">
									<span class="badge badge-primary">Official</span>
								</a>
							{% endif %}
							{% if user.affiliation %}
								<span class="d-block text-muted"><small>{{ user.affiliation | truncate(20) }}</small></span>
							{% endif %}
						</td>
						<td class="team-email d-none d-md-table-cell d-lg-table-cell" value="{{ user.email }}">
							{% if user.email %}
								<a href="mailto:{{ user.email }}" target="_blank">{{ user.email | truncate(32) }}</a>
							{% endif %}
						</td>
						<td class="team-website text-center">
							{% if user.website %}
								<a href="{{ user.website }}" target="_blank">
									<i class="btn-fa fas fa-external-link-alt" data-toggle="tooltip" data-placement="top"
									   title="{{ user.website }}" aria-hidden="true"></i>
								</a>
							{% endif %}
						</td>
						<td class="team-country" value="{{ user.country if user.country is not none }}">
							<span>{% if user.country %}{{ lookup_country_code(user.country) }}{% endif %}</span>
						</td>
						<td class="team-admin d-md-table-cell d-lg-table-cell text-center" value="{{ user.type }}">
							{% if user.type == 'admin' %}
								<span class="badge badge-primary">admin</span>
							{% endif %}
						</td>
						<td class="team-verified d-md-table-cell d-lg-table-cell text-center" value="{{ user.verified }}">
							{% if user.verified %}
								<span class="badge badge-success">verified</span>
							{% endif %}
						</td>
						<td class="team-hidden d-md-table-cell d-lg-table-cell text-center" value="{{ user.hidden }}">
							{% if user.hidden %}
								<span class="badge badge-danger">hidden</span>
							{% endif %}
						</td>
						<td class="team-banned d-md-table-cell d-lg-table-cell text-center" value="{{ user.banned }}">
							{% if user.banned %}
								<span class="badge badge-danger">banned</span>
							{% endif %}
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
			{% if pages > 1 %}
			<div class="text-center">Page
				<br>
				{% if curr_page != 1 %}<a href="{{ url_for('admin.users_listing', page=curr_page - 1) }}">&lt;&lt;&lt;</a>{% endif %}
				{% for page in range(1, pages + 1) %}
					{% if curr_page != page %}
						<a href="{{ url_for('admin.users_listing', page=page) }}">{{ page }}</a>
					{% else %}
						<b>{{ page }}</b>
					{% endif %}
				{% endfor %}
				{% if curr_page != pages %}<a href="{{ url_for('admin.users_listing', page=curr_page + 1) }}">&gt;&gt;&gt;</a>{% endif %}
			</div>
			{% endif %}
		</div>
	</div>
</div>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('views.themes', theme='admin', path='js/users/users.js') }}"></script>
{% endblock %}